### PR TITLE
PSR2 + remove old comment + remove useless files

### PR DESCRIPTION
**Pull request by itkg-ngilain**

### CODE REVIEW

**Comment by nicolasThal** [comment]
You could go a little further and use Phake instead of the Phpunit mockbuilder in the tests.

Still :+1: for the part you have done.

**Comment by itkg-ngilain** [comment]
That's a good idea, I'll try to do an update with these mofications.

**Comment by itkg-ngilain** [comment]
@nicolasThal : only one test file needed to be updated to use Phake. Update done

**Comment by nicolasThal** [comment]
:+1:

**Pull request merged**
